/**
 * Launch metadata for the agents in the ACP registry, as of the last explicit
 * refresh.
 *
 * Generated by `scripts/refresh-acp-registry.mjs`; do not edit by hand. Pinned
 * on purpose: the versions below are what a registration naming an agent will
 * run, so they change in a reviewed commit rather than from whatever the
 * network answers during a dispatch. Nothing reads the network at run time.
 *
 * @see https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json
 */
/**
 * An agent distributed through a package runner.
 *
 * `command` plus `args` launches it with no prior install. `bins` names the
 * executables the package installs, so a registration can prefer an already
 * installed copy: it starts immediately, where the runner re-resolves the
 * package and may download it first.
 */
export interface AcpRegistryRunnerLaunch {
    kind: "npx" | "uvx";
    command: string;
    args: readonly string[];
    /**
     * Read from the package manifest, never derived from its name — `@google/gemini-cli`
     * installs `gemini`. Empty means no local candidate is known, not that none
     * exists: uvx packages do not publish their script names where the refresh reads.
     */
    bins: readonly string[];
    /** Arguments that follow the executable when a local copy is used instead. */
    runnerArgs: readonly string[];
}
/**
 * An agent shipped as a platform executable.
 *
 * Nothing here downloads or extracts it, so the operator names the executable
 * and only the arguments come from the registry. Kept per target because they
 * genuinely differ by platform for at least one agent.
 */
export interface AcpRegistryBinaryLaunch {
    kind: "binary";
    /** Keyed `<platform>-<arch>`, e.g. `darwin-aarch64`, exactly as upstream states them. */
    argsByTarget: Readonly<Record<string, readonly string[]>>;
}
/** How an agent is launched, once an operator has whatever it needs installed. */
export type AcpRegistryLaunch = AcpRegistryRunnerLaunch | AcpRegistryBinaryLaunch;
/** One agent the registry lists, reduced to what a registration needs. */
export interface AcpRegistryAgent {
    id: string;
    name: string;
    version: string;
    launch: AcpRegistryLaunch;
}
/** Upstream registry document this snapshot was taken from. */
export declare const ACP_REGISTRY_SOURCE = "https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json";
/** Upstream registry schema version at the time of the refresh. */
export declare const ACP_REGISTRY_VERSION = "1.0.0";
/** Every listed agent, by ascending id. */
export declare const ACP_REGISTRY_AGENTS: readonly AcpRegistryAgent[];
