/**
 * Launch metadata for the agents in the ACP registry, as of the last explicit
 * refresh.
 *
 * Generated by `scripts/refresh-acp-registry.mjs`; do not edit by hand. Pinned
 * on purpose: the versions below are what a registration naming an agent will
 * run, so they change in a reviewed commit rather than from whatever the
 * network answers during a dispatch. Nothing reads the network at run time.
 *
 * @see https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json
 */

/**
 * An agent distributed through a package runner.
 *
 * `command` plus `args` launches it with no prior install. `bins` names the
 * executables the package installs, so a registration can prefer an already
 * installed copy: it starts immediately, where the runner re-resolves the
 * package and may download it first.
 */
export interface AcpRegistryRunnerLaunch {
  kind: "npx" | "uvx";
  command: string;
  args: readonly string[];
  /**
   * Read from the package manifest, never derived from its name — `@google/gemini-cli`
   * installs `gemini`. Empty means no local candidate is known, not that none
   * exists: uvx packages do not publish their script names where the refresh reads.
   */
  bins: readonly string[];
  /** Arguments that follow the executable when a local copy is used instead. */
  runnerArgs: readonly string[];
}

/**
 * An agent shipped as a platform executable.
 *
 * Nothing here downloads or extracts it, so the operator names the executable
 * and only the arguments come from the registry. Kept per target because they
 * genuinely differ by platform for at least one agent.
 */
export interface AcpRegistryBinaryLaunch {
  kind: "binary";
  /** Keyed `<platform>-<arch>`, e.g. `darwin-aarch64`, exactly as upstream states them. */
  argsByTarget: Readonly<Record<string, readonly string[]>>;
}

/** How an agent is launched, once an operator has whatever it needs installed. */
export type AcpRegistryLaunch = AcpRegistryRunnerLaunch | AcpRegistryBinaryLaunch;

/** One agent the registry lists, reduced to what a registration needs. */
export interface AcpRegistryAgent {
  id: string;
  name: string;
  version: string;
  launch: AcpRegistryLaunch;
}

/** Upstream registry document this snapshot was taken from. */
export const ACP_REGISTRY_SOURCE = "https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json";

/** Upstream registry schema version at the time of the refresh. */
export const ACP_REGISTRY_VERSION = "1.0.0";

/** Every listed agent, by ascending id. */
export const ACP_REGISTRY_AGENTS: readonly AcpRegistryAgent[] = [
  {
    "id": "agoragentic-acp",
    "name": "Agoragentic",
    "version": "1.3.0",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "agoragentic-mcp@1.3.0",
        "--acp"
      ],
      "bins": [
        "agoragentic-mcp"
      ],
      "runnerArgs": [
        "--acp"
      ]
    }
  },
  {
    "id": "amp-acp",
    "name": "Amp",
    "version": "0.9.0",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [],
        "darwin-x86_64": [],
        "linux-aarch64": [],
        "linux-x86_64": [],
        "windows-x86_64": []
      }
    }
  },
  {
    "id": "antigravity-acp",
    "name": "Google Antigravity",
    "version": "1.0.0",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [],
        "linux-x86_64": [
          "--uid="
        ],
        "linux-aarch64": [
          "--uid="
        ],
        "windows-x86_64": [],
        "windows-aarch64": []
      }
    }
  },
  {
    "id": "auggie",
    "name": "Auggie CLI",
    "version": "0.35.0",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@augmentcode/auggie@0.35.0",
        "--acp"
      ],
      "bins": [
        "auggie"
      ],
      "runnerArgs": [
        "--acp"
      ]
    }
  },
  {
    "id": "autohand",
    "name": "Autohand Code",
    "version": "0.2.1",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@autohandai/autohand-acp@0.2.1"
      ],
      "bins": [
        "autohand-acp"
      ],
      "runnerArgs": []
    }
  },
  {
    "id": "claude-acp",
    "name": "Claude Agent",
    "version": "0.70.0",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@agentclientprotocol/claude-agent-acp@0.70.0"
      ],
      "bins": [
        "claude-agent-acp"
      ],
      "runnerArgs": []
    }
  },
  {
    "id": "cline",
    "name": "Cline",
    "version": "3.0.56",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "cline@3.0.56",
        "--acp"
      ],
      "bins": [
        "cline"
      ],
      "runnerArgs": [
        "--acp"
      ]
    }
  },
  {
    "id": "codebuddy-code",
    "name": "Codebuddy Code",
    "version": "2.137.1",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@tencent-ai/codebuddy-code@2.137.1",
        "--acp"
      ],
      "bins": [
        "cbc",
        "cbc-prewarm",
        "codebuddy",
        "codebuddy-code"
      ],
      "runnerArgs": [
        "--acp"
      ]
    }
  },
  {
    "id": "codex-acp",
    "name": "Codex",
    "version": "1.6.2",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@agentclientprotocol/codex-acp@1.6.2"
      ],
      "bins": [
        "codex-acp"
      ],
      "runnerArgs": []
    }
  },
  {
    "id": "cortex-code",
    "name": "Cortex Code",
    "version": "1.0.73",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp",
          "serve"
        ],
        "darwin-x86_64": [
          "acp",
          "serve"
        ],
        "linux-x86_64": [
          "acp",
          "serve"
        ],
        "linux-aarch64": [
          "acp",
          "serve"
        ],
        "windows-x86_64": [
          "acp",
          "serve"
        ],
        "windows-aarch64": [
          "acp",
          "serve"
        ]
      }
    }
  },
  {
    "id": "corust-agent",
    "name": "Corust Agent",
    "version": "0.6.0",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [],
        "darwin-x86_64": [],
        "linux-x86_64": [],
        "windows-x86_64": []
      }
    }
  },
  {
    "id": "crow-cli",
    "name": "crow-cli",
    "version": "0.1.24",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp"
        ],
        "darwin-x86_64": [
          "acp"
        ],
        "linux-aarch64": [
          "acp"
        ],
        "linux-x86_64": [
          "acp"
        ],
        "windows-x86_64": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "cursor",
    "name": "Cursor",
    "version": "2026.08.11",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp"
        ],
        "darwin-x86_64": [
          "acp"
        ],
        "linux-aarch64": [
          "acp"
        ],
        "linux-x86_64": [
          "acp"
        ],
        "windows-aarch64": [
          "acp"
        ],
        "windows-x86_64": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "deepagents",
    "name": "DeepAgents",
    "version": "0.1.7",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "deepagents-acp@0.1.7"
      ],
      "bins": [
        "deepagents-acp"
      ],
      "runnerArgs": []
    }
  },
  {
    "id": "devin",
    "name": "Devin",
    "version": "3000.4.25",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp"
        ],
        "darwin-x86_64": [
          "acp"
        ],
        "linux-aarch64": [
          "acp"
        ],
        "linux-x86_64": [
          "acp"
        ],
        "windows-aarch64": [
          "acp"
        ],
        "windows-x86_64": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "dimcode",
    "name": "DimCode",
    "version": "0.3.18",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "dimcode@0.3.18",
        "acp"
      ],
      "bins": [
        "dim",
        "dimcode"
      ],
      "runnerArgs": [
        "acp"
      ]
    }
  },
  {
    "id": "dirac",
    "name": "Dirac",
    "version": "0.4.37",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "dirac-cli@0.4.37",
        "--acp"
      ],
      "bins": [
        "dirac"
      ],
      "runnerArgs": [
        "--acp"
      ]
    }
  },
  {
    "id": "factory-droid",
    "name": "Factory Droid",
    "version": "0.200.0",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "droid@0.200.0",
        "exec",
        "--output-format",
        "acp-daemon"
      ],
      "bins": [
        "droid"
      ],
      "runnerArgs": [
        "exec",
        "--output-format",
        "acp-daemon"
      ]
    }
  },
  {
    "id": "fast-agent",
    "name": "fast-agent",
    "version": "0.10.1",
    "launch": {
      "kind": "uvx",
      "command": "uvx",
      "args": [
        "fast-agent-acp==0.10.1",
        "-x"
      ],
      "bins": [],
      "runnerArgs": [
        "-x"
      ]
    }
  },
  {
    "id": "gemini",
    "name": "Gemini CLI",
    "version": "0.56.0",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@google/gemini-cli@0.56.0",
        "--acp"
      ],
      "bins": [
        "gemini"
      ],
      "runnerArgs": [
        "--acp"
      ]
    }
  },
  {
    "id": "github-copilot-cli",
    "name": "GitHub Copilot",
    "version": "1.0.80",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@github/copilot@1.0.80",
        "--acp"
      ],
      "bins": [
        "copilot"
      ],
      "runnerArgs": [
        "--acp"
      ]
    }
  },
  {
    "id": "glm-acp-agent",
    "name": "GLM Agent",
    "version": "1.6.0",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "glm-acp-agent@1.6.0"
      ],
      "bins": [
        "glm-acp-agent"
      ],
      "runnerArgs": []
    }
  },
  {
    "id": "goose",
    "name": "goose",
    "version": "1.46.0",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp"
        ],
        "darwin-x86_64": [
          "acp"
        ],
        "linux-aarch64": [
          "acp"
        ],
        "linux-x86_64": [
          "acp"
        ],
        "windows-x86_64": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "grok-build",
    "name": "Grok Build",
    "version": "1.0.8",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@xai-official/grok@1.0.8",
        "agent",
        "stdio"
      ],
      "bins": [
        "grok"
      ],
      "runnerArgs": [
        "agent",
        "stdio"
      ]
    }
  },
  {
    "id": "harn",
    "name": "Harn",
    "version": "0.10.109",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "serve",
          "acp"
        ],
        "darwin-x86_64": [
          "serve",
          "acp"
        ],
        "linux-aarch64": [
          "serve",
          "acp"
        ],
        "linux-x86_64": [
          "serve",
          "acp"
        ],
        "windows-x86_64": [
          "serve",
          "acp"
        ]
      }
    }
  },
  {
    "id": "junie",
    "name": "Junie",
    "version": "2913.6.0",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "--acp=true"
        ],
        "darwin-x86_64": [
          "--acp=true"
        ],
        "linux-aarch64": [
          "--acp=true"
        ],
        "linux-x86_64": [
          "--acp=true"
        ],
        "windows-x86_64": [
          "--acp=true"
        ],
        "windows-aarch64": [
          "--acp=true"
        ]
      }
    }
  },
  {
    "id": "kilo",
    "name": "Kilo",
    "version": "7.4.23",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@kilocode/cli@7.4.23",
        "acp"
      ],
      "bins": [
        "kilo",
        "kilocode"
      ],
      "runnerArgs": [
        "acp"
      ]
    }
  },
  {
    "id": "kimi",
    "name": "Kimi CLI",
    "version": "1.49.0",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp"
        ],
        "linux-aarch64": [
          "acp"
        ],
        "linux-x86_64": [
          "acp"
        ],
        "windows-aarch64": [
          "acp"
        ],
        "windows-x86_64": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "minion-code",
    "name": "Minion Code",
    "version": "0.1.44",
    "launch": {
      "kind": "uvx",
      "command": "uvx",
      "args": [
        "minion-code@0.1.44",
        "acp"
      ],
      "bins": [],
      "runnerArgs": [
        "acp"
      ]
    }
  },
  {
    "id": "mistral-vibe",
    "name": "Mistral Vibe",
    "version": "2.24.1",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [],
        "darwin-x86_64": [],
        "linux-aarch64": [],
        "linux-x86_64": [],
        "windows-x86_64": []
      }
    }
  },
  {
    "id": "nova",
    "name": "Nova",
    "version": "1.1.35",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@compass-ai/nova@1.1.35",
        "acp"
      ],
      "bins": [
        "compass",
        "nova"
      ],
      "runnerArgs": [
        "acp"
      ]
    }
  },
  {
    "id": "opencode",
    "name": "OpenCode",
    "version": "1.18.21",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp"
        ],
        "darwin-x86_64": [
          "acp"
        ],
        "linux-aarch64": [
          "acp"
        ],
        "linux-x86_64": [
          "acp"
        ],
        "windows-aarch64": [
          "acp"
        ],
        "windows-x86_64": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "pi-acp",
    "name": "pi ACP",
    "version": "0.0.33",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "pi-acp@0.0.33"
      ],
      "bins": [
        "pi-acp"
      ],
      "runnerArgs": []
    }
  },
  {
    "id": "poolside",
    "name": "Poolside",
    "version": "1.0.16",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp"
        ],
        "darwin-x86_64": [
          "acp"
        ],
        "linux-aarch64": [
          "acp"
        ],
        "linux-x86_64": [
          "acp"
        ],
        "windows-aarch64": [
          "acp"
        ],
        "windows-x86_64": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "qoder",
    "name": "Qoder CLI",
    "version": "0.2.14",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@qoder-ai/qodercli@0.2.14",
        "--acp"
      ],
      "bins": [
        "qoder",
        "qodercli"
      ],
      "runnerArgs": [
        "--acp"
      ]
    }
  },
  {
    "id": "qwen-code",
    "name": "Qwen Code",
    "version": "0.21.15",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@qwen-code/qwen-code@0.21.15",
        "--acp",
        "--experimental-skills"
      ],
      "bins": [
        "qwen"
      ],
      "runnerArgs": [
        "--acp",
        "--experimental-skills"
      ]
    }
  },
  {
    "id": "sigit",
    "name": "siGit Code",
    "version": "1.5.2",
    "launch": {
      "kind": "npx",
      "command": "npx",
      "args": [
        "-y",
        "@smbcloud/sigit@1.5.2"
      ],
      "bins": [
        "sigit"
      ],
      "runnerArgs": []
    }
  },
  {
    "id": "stakpak",
    "name": "Stakpak",
    "version": "0.3.88",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp"
        ],
        "darwin-x86_64": [
          "acp"
        ],
        "linux-aarch64": [
          "acp"
        ],
        "linux-x86_64": [
          "acp"
        ],
        "windows-x86_64": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "vtcode",
    "name": "VT Code",
    "version": "0.96.14",
    "launch": {
      "kind": "binary",
      "argsByTarget": {
        "darwin-aarch64": [
          "acp"
        ],
        "darwin-x86_64": [
          "acp"
        ],
        "linux-x86_64": [
          "acp"
        ],
        "windows-x86_64": [
          "acp"
        ]
      }
    }
  }
];
